name: Update Final Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Menjalankan skrip setiap hari pada tengah malam UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python nama_file_skrip_anda.py # Ganti nama file ini dengan nama skrip Python Anda

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Finalplay.m3u
          git commit -m "Auto-update playlist: $(date)" || echo "No changes to commit"
          git push
