name: Update Playlist

on:
  schedule:
    - cron: "0 */6 * * *"   # jalan tiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt   # 👈 ambil dari folder scripts

      - name: Run Python script
        run: python scripts/generate_playlist.py

      - name: Commit and push if changed
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Finalplay.m3u last_update.txt || true
          git commit -m "🔄 Auto update playlist [$(date)]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }} HEAD:main
